name: CI

on:
  push:
    branches: [ "main" ]

defaults:
  run:
    shell: pwsh

jobs:
  ci_build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Build FrameworkDetector
      run: ./scripts/build.ps1 -Configuration ${{ matrix.configuration }}

    - name: Test FrameworkDetector
      run: ./scripts/test.ps1 -Configuration ${{ matrix.configuration }}

  ci_package:
    runs-on: windows-latest
    needs: ci_build
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Build FrameworkDetector NuGets
      run: ./scripts/build-nuget-release.ps1

    - name: Build FrameworkDetector.CLI Release
      run: ./scripts/build-cli-release.ps1
