name: Publish

on: workflow_dispatch

defaults:
  run:
    shell: pwsh

jobs:
  publish_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Build FrameworkDetector NuGet
      run: ./scripts/build-nuget-release.ps1

    - name: Build FrameworkDetector.CLI Release
      run: ./scripts/build-cli-release.ps1
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FrameworkDetector.CLI Release
        path: ./bld/FrameworkDetector
